/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -t -T C:\Users\abrka\PhpstormProjects\GetCake\public\models\fruit_cream_cake\scene.gltf -o C:\Users\abrka\PhpstormProjects\GetCake\src\components\models\fruit_cream_cake\Model.tsx 
Files: C:\Users\abrka\PhpstormProjects\GetCake\public\models\fruit_cream_cake\scene.gltf [8.01KB] > C:\Users\abrka\PhpstormProjects\GetCake\src\components\models\fruit_cream_cake\scene-transformed.glb [680.37KB] (-8394%)
Author: mirador360 (https://sketchfab.com/mirador360)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-chocolate-cake-9c9f21a0a5404b4083be16376415e7a7
Title: White Chocolate Cake
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshBasicMaterial
    Material_1: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/fruit_cream_cake/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} position={[-309.372, 10862.374, -11058.506]} rotation={[-0.018, 0, -3.138]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Material_1} position={[-309.372, 10862.374, -11058.506]} rotation={[-0.018, 0, -3.138]} />
    </group>
  )
}

useGLTF.preload('/models/fruit_cream_cake/scene-transformed.glb')
