/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -t -T C:\Users\abrka\PhpstormProjects\GetCake\public\models\fruit_cake_slice\scene.gltf -o C:\Users\abrka\PhpstormProjects\GetCake\src\components\models\fruit_cake_slice\Model.tsx 
Files: C:\Users\abrka\PhpstormProjects\GetCake\public\models\fruit_cake_slice\scene.gltf [4.57KB] > C:\Users\abrka\PhpstormProjects\GetCake\src\components\models\fruit_cake_slice\scene-transformed.glb [339.75KB] (-7334%)
Author: matousekfoto (https://sketchfab.com/matousekfoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fruit-cake-slice-7b9a33386eab4dd986aa0980054ead3c
Title: Fruit Cake Slice
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    FruitCakeSlice_FruitCakeSlice_u1_v1_0: THREE.Mesh
  }
  materials: {
    FruitCakeSlice_u1_v1: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/fruit_cake_slice/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FruitCakeSlice_FruitCakeSlice_u1_v1_0.geometry} material={materials.FruitCakeSlice_u1_v1} position={[0, -0.15, 0.128]} rotation={[(-1.59), 0, -Math.PI / 2]} scale={0.027} />
    </group>
  )
}

useGLTF.preload('/models/fruit_cake_slice/scene-transformed.glb')
