/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -t -T C:\Users\abrka\PhpstormProjects\GetCake\public\models\strawberry_cream_cake_shortcake\scene.gltf -o C:\Users\abrka\PhpstormProjects\GetCake\src\components\models\strawberry_cream_cake_shortcake\Model.tsx 
Files: C:\Users\abrka\PhpstormProjects\GetCake\public\models\strawberry_cream_cake_shortcake\scene.gltf [15.54KB] > C:\Users\abrka\PhpstormProjects\GetCake\src\components\models\strawberry_cream_cake_shortcake\scene-transformed.glb [2.15MB] (-13764%)
Author: M Parkinson (https://sketchfab.com/chimaera_studio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/strawberry-cream-cake-shortcake-9bfd31a63aa14e1e8261d95358d0b0fa
Title: Strawberry Cream Cake (shortcake)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    model_tex_u1_v1_0: THREE.Mesh
  }
  materials: {
    tex_u1_v1: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/strawberry_cream_cake_shortcake/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_tex_u1_v1_0.geometry} material={materials.tex_u1_v1} rotation={[-Math.PI / 2, 0, 0]} scale={2}/>
    </group>
  )
}

useGLTF.preload('/models/strawberry_cream_cake_shortcake/scene-transformed.glb')
